num = float(input('Digite um numero e pressione enter para calcular a sua tabuada:'))
titulo1 = 'Tabuada da multiplicação {}'.format(num)
print('{:=^30}'.format(titulo1))
print('{}x{}={}'.format(num,1,num))
print('{}x{}={}'.format(num,2,2*num))
print('{}x{}={}'.format(num,3,3*num))
print('{}x{}={}'.format(num,4,4*num))
print('{}x{}={}'.format(num,5,5*num))
print('{}x{}={}'.format(num,6,6*num))
print('{}x{}={}'.format(num,7,7*num))
print('{}x{}={}'.format(num,8,8*num))
print('{}x{}={}'.format(num,9,9*num))
print('{}x{}={}'.format(num,10,10*num))

titulo2 = 'Tabuada da soma {}'.format(num)
print('{:=^30}'.format(titulo2))
print('{}+{}={}'.format(num,1,num+1))
print('{}+{}={}'.format(num,2,2+num))
print('{}+{}={}'.format(num,3,3+num))
print('{}+{}={}'.format(num,4,4+num))
print('{}+{}={}'.format(num,5,5+num))
print('{}+{}={}'.format(num,6,6+num))
print('{}+{}={}'.format(num,7,7+num))
print('{}+{}={}'.format(num,8,8+num))
print('{}+{}={}'.format(num,9,9+num))
print('{}+{}={}'.format(num,10,10+num))


